// SPDX-License-Identifier: GPL-2.0
#pragma once

// Buffer size should be a power of 2 to keep arithmetic operations correct
#define DISCOVERY_BUFFER_MAX_DATA_SIZE 8192 // 8 KiB
#define DISCOVERY_MAX_SESSIONS 8192
#define DISCOVERY_EVENT_QUEUE_SIZE 512

#define DISCOVERY_MAX_HTTP_REQUEST_LENGTH DISCOVERY_BUFFER_MAX_DATA_SIZE
#define DISCOVERY_MIN_HTTP_REQUEST_LENGTH 16

#define DISCOVERY_LOG_MAX_FORMAT_LENGTH 128
#define DISCOVERY_LOG_MAX_MESSAGE_LENGTH DISCOVERY_LOG_MAX_FORMAT_LENGTH + 32
#define DISCOVERY_LOG_MAX_ARGS_COUNT 8
