// SPDX-License-Identifier: GPL-2.0
#pragma once

#define DISCOVERY_BUFFER_MAX_DATA_SIZE 10240 // 10 KiB
#define DISCOVERY_MAX_SESSIONS 8192
#define DISCOVERY_EVENT_QUEUE_SIZE 512

#define DISCOVERY_MAX_HTTP_REQUEST_LENGTH DISCOVERY_BUFFER_MAX_DATA_SIZE
#define DISCOVERY_MIN_HTTP_REQUEST_LENGTH 16

#define DISCOVERY_LOG_MAX_MESSAGE_LENGTH 128
