name: Set environment variables

inputs:
  build-type:
    description: Release or Debug
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        buildType=${{ inputs.build-type }}
        printf "CAPITALISED_BUILD_TYPE=%s\n" "${buildType}" >> $GITHUB_ENV
        printf "LOWERCASE_BUILD_TYPE=%s\n" "${buildType,,}" >> $GITHUB_ENV
        
        versionPropertiesPath="${{ github.workspace }}/version.properties"
        versionString="$(cat "${versionPropertiesPath}")"
        versionTag="version="
        version="$(printf "%s" "${versionString}" | sed -e "s/^"${versionTag}"//")"
        printf "ARTIFACT_VERSION=%s\n" "${version}" >> $GITHUB_ENV
        
        printf "RELEASE_PATH=%s\n" "${{ github.workspace }}/build/Release" >> $GITHUB_ENV
        
        repositoryName="$(printf "%s" "${{ github.repository }}" | sed -e "s/^${{ github.repository_owner }}\///")"
        printf "LOWERCASE_REPOSITORY_NAME=%s\n" "${repositoryName,,}" >> $GITHUB_ENV
