name: Configure
description: Configure build environment

runs:
  using: composite
  steps:
    - name: Configure
      shell: bash
      run: >-
        docker run -i --rm
        -w ${{ github.workspace }}
        --user=$(id -u):$(id -g)
        -v /home/runner:/home/runner
        -v /etc/passwd:/etc/passwd
        ${{ env.IMAGE_NAME }}:latest
        cmake
        -S .
        -B ${{ env.BUILD_PATH }}
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        -DCMAKE_C_COMPILER=gcc
        '-DCMAKE_CXX_COMPILER=g++'
        -DBUILD_TESTS=ON
        -DPROJECT_VERSION=${{ env.PROJECT_VERSION }}
