name: Configure

runs:
  using: composite
  steps:
    - name: Configure
      shell: bash
      run: >-
        cmake
        -S . 
        -B ${{ env.BUILD_PATH }}
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} 
        -DCMAKE_C_COMPILER=gcc 
        '-DCMAKE_CXX_COMPILER=g++'
        -DBUILD_TESTS=ON 
        -DPROJECT_VERSION=${{ env.PROJECT_VERSION }}