name: Load tests
description: Run load tests

runs:
  using: composite
  steps:
    - name: Create venv and install requirements
      shell: bash
      run: |
        python -m venv testvenv
        source testvenv/bin/activate
        pip install -r "${{ env.LOAD_TESTING_PATH }}/requirements.txt"
    - name: Create logs directory
      shell: bash
      run: mkdir logs
    - name: Load tests
      shell: bash
      run: |
        source testvenv/bin/activate
        cd ${{ env.LOAD_TESTING_PATH }}
        /bin/bash test_load.sh ${{ env.DISCOVERY_BIN_PATH }} ${{ github.workspace }}/logs 5 5 30m
      continue-on-error: true
    - name: Upload log archive
      uses: actions/upload-artifact@v3
      with:
        name: log-archive
        path: ${{ github.workspace }}/logs