name: Build and test Release/Debug binaries

inputs:
  build-type:
    description: Release or Debug
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Checkout source code of the repository
      uses: actions/checkout@v3

    - name: Update packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Set environment variables
      shell: bash
      run: |
        buildType=${{ inputs.build-type }}
        printf "CAPITALISED_BUILD_TYPE=%s" "${buildType}" >> $GITHUB_ENV
        printf "LOWERCASE_BUILD_TYPE=%s" "${buildType,,}" >> $GITHUB_ENV

    - name: Install requirements
      shell: bash
      run: |
        sudo apt-get install -y libelf-dev
        sudo apt-get install -y libboost-all-dev
        sudo apt-get install -y libfmt-dev
        sudo apt-get install -y clang
        pip install cmake==3.23.3
        pip install conan==2.0
        conan profile detect
        conan install . --build=missing -s build_type=${{ env.CAPITALISED_BUILD_TYPE }}

    - name: Configure Release
      shell: bash
      run: cmake --preset conan-${{ env.LOWERCASE_BUILD_TYPE }} -DBUILD_TESTS=OFF
      if: ${{ env.LOWERCASE_BUILD_TYPE == 'release' }}

    - name: Configure Debug
      shell: bash
      run: cmake --preset conan-${{ env.LOWERCASE_BUILD_TYPE }}
      if: ${{ env.LOWERCASE_BUILD_TYPE == 'debug' }}

    - name: Build
      shell: bash
      run: cmake --build --preset conan-${{ env.LOWERCASE_BUILD_TYPE }}

    - name: Test
      shell: bash
      run: ctest --preset conan-${{ env.LOWERCASE_BUILD_TYPE }}
