name: Test
description: Run component tests

runs:
  using: composite
  steps:
    - name: Install requirements
      shell: bash
      run: |
        python -m venv testvenv
        source testvenv/bin/activate
        pip install -r "${{ env.COMPONENT_TESTING_PATH }}/requirements.txt"
    - name: Component tests
      shell: bash
      run: sudo testvenv/bin/pytest ${{ env.COMPONENT_TESTING_PATH }} -s -v --discovery_path="${{ env.DISCOVERY_BIN_PATH }}"
