name: Build and test Release/Debug binaries

on:
  workflow_call:
    inputs:
      build-type:
        description: Release or Debug
        required: true
        type: string

jobs:
  build-x86-64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code of the repository
        uses: actions/checkout@v3

      - name: Update packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Set environment variables
        run: |
          buildType=${{ inputs.build-type }}
          echo "CAPITALISED_BUILD_TYPE="${buildType}"" >> $GITHUB_ENV
          echo "LOWERCASE_BUILD_TYPE="${buildType,,}"" >> $GITHUB_ENV

      - name: Install requirements
        run: |
          sudo apt-get install -y libelf-dev
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y libfmt-dev
          sudo apt-get install -y clang
          pip install cmake==3.23.3
          pip install conan==2.0
          conan profile detect
          conan install . --build=missing -s build_type=${{ env.CAPITALISED_BUILD_TYPE }}
          
      - name: Configure Release
        run: cmake --preset conan-${{ env.LOWERCASE_BUILD_TYPE }} -DBUILD_TESTS=OFF
        if: ${{ env.LOWERCASE_BUILD_TYPE == 'release' }}

      - name: Configure Debug
        run: cmake --preset conan-${{ env.LOWERCASE_BUILD_TYPE }}
        if: ${{ env.LOWERCASE_BUILD_TYPE == 'debug' }}

      - name: Build
        run: cmake --build --preset conan-${{ env.LOWERCASE_BUILD_TYPE }}

      - name: Test
        run: ctest --preset conan-${{ env.LOWERCASE_BUILD_TYPE }}
