name: Build and test Debug binaries on push

on:
  push:
    branches:
      - main

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code of the repository
        uses: actions/checkout@v3

      - name: Build and test
        uses: ./.github/actions/action.yaml
        with:
          build-type: Debug
