name: Build and test Release binaries on main branch

on:
  push:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code of the repository
        uses: actions/checkout@v3

      - name: Build and test
        uses: ./.github/actions/build-and-test
        with:
          build-type: Release

      - name: Zip built binaries
        run: |
          versionPropertiesPath="${{ github.workspace }}/version.properties"
          versionString="$(cat "${versionPropertiesPath}")"
          versionTag="version="
          version="$(printf "%s" "${versionString}" | sed -e "s/^"$versionTag"//")"
          artifactName="${version}"-"$(date +%s)".zip
          
          buildPath=${{ github.workspace }}/build/Release 
          licensePath=${{ github.workspace }}/LICENSE
          
          zip -r "${artifactName}" "${buildPath}" "${licensePath}"
