name: Build and test Release binaries on merge

on:
  push:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        uses: ./.github/workflows/build-and-test.yaml
        with:
          build-type: Release
